databases:
  - name: backend
    plan: free
    databaseName: open_sacco
    user: admin

services:
  - type: web
    plan: free
    name: backend
    runtime: python
    buildCommand: |
      # Install necessary build tools
      apt-get update && apt-get install -y gcc libffi-dev
      # Execute custom build script
      build.sh
    startCommand: "python -m gunicorn backend.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: backend
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
