# Generated by Django 4.2.13 on 2026-02-03 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('FI', 'Finance Officer'), ('LO', 'Loan Officer'), ('MA', 'Manager'), ('OP', 'Operation Manager'), ('AD', 'Admin'), ('AC', 'Accountant')], default='AC', max_length=2),
        ),
    ]
