# Generated by Django 4.2.13 on 2026-02-03 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('FI', 'Finance Officer'), ('AC', 'Accountant'), ('OP', 'Operation Manager'), ('MA', 'Manager'), ('LO', 'Loan Officer'), ('AD', 'Admin')], default='AC', max_length=2),
        ),
    ]
