# Generated by Django 4.2.13 on 2026-02-03 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('AC', 'Accountant'), ('MA', 'Manager'), ('FI', 'Finance Officer'), ('LO', 'Loan Officer'), ('AD', 'Admin'), ('OP', 'Operation Manager')], default='AC', max_length=2),
        ),
    ]
